### ISSUE TITLE
Error in using the new version of lattice

### ISSUE THREAD

**Issue by gfarnadi** [tensorflow/lattice#43]
Hi,

I was able to work with Lattice v 0.9.9, but after upgrading the code with v 2.0 a few days ago, I am not able to run my code anymore. I keep receiving the following error when I import tensorflow_lattice:
"AttributeError: module 'tensorflow.python.keras.utils.losses_utils' has no attribute 'ReductionV2'"

Can you please let me know how to resolve this issue?

Thanks.

**Comment by mmilanifard** [comment]
ReductionV2 was added in TF 1.14. TF Lattice supports TF >= 1.15. You are likely using an older version of TF. Try upgrading to a new version of TF.

To get the latest TF (2.1 as of now):
pip install --upgrade tensorflow

To upgrade to the minimum requirement for TF Lattice:
pip install --upgrade tensorflow==1.15
